version: "3.9"

services:
  memgpt_server:
    container_name: memgpt_server
    image: memgpt/backend
    build:
      context: ./llm_memory
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8091:8080"
    depends_on:
      - memgpt_pgdb
    networks:
      - chat_network

  memgpt_frontend:
    container_name: memgpt_frontend
    image: memgpt/frontend
    build:
      context: ./llm_memory_ui
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./configs:/etc/nginx/conf.d
    networks:
      - chat_network

  memgpt_pgdb:
    container_name: memgpt_pgdb
    # image: pgvector/pgvector:pg16
    image: ankane/pgvector:v0.5.1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=memgpt
    volumes:
      - pgdata_memgpt:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chat_network

volumes:
  pgdata_memgpt:
    external: true

networks:
  chat_network:
    external: true
