version: '3.9'

services:

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=memgpt
    volumes:
      - pgdata_memgpt:/var/lib/postgresql/data

volumes:
  pgdata_memgpt:
    external: true
