version: '3.9'

services:

  frontend:
    container_name: memgpt_frontend
    image: memgpt/frontend
    build: 
      context: ./llm_memory_ui
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./configs:/etc/nginx/conf.d

  db:
    container_name: memgpt_pgdb
    # image: pgvector/pgvector:pg16
    image: ankane/pgvector:v0.5.1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=memgpt
    volumes:
      - pgdata_memgpt:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  pgdata_memgpt:
    external: true
